### ISSUE TITLE
Bug report 

### ISSUE THREAD

**Issue by groundbreakingmc** [james090500/VelocityWhitelist#4]
Im just gettinf error

[18:38:54 ERROR]: Couldn't pass LoginEvent to velocitywhitelist
java.lang.NullPointerException: Cannot invoke "java.util.Set.contains(Object)" because the return value of "com.james090500.VelocityWhitelist.config.Configs.getWhitelist()" is null
        at com.james090500.VelocityWhitelist.helpers.WhitelistHelper.check(WhitelistHelper.java:27) ~[?:?]
        at com.james090500.VelocityWhitelist.listeners.JoinListener.onPlayerJoin(JoinListener.java:20) ~[?:?]
        at com.james090500.VelocityWhitelist.listeners.Lmbda$53.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[Velocity-3.3-346.jar:3.3.0-SNAPSHOT (git-59567512-b346)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[Velocity-3.3-346.jar:3.3.0-SNAPSHOT (git-59567512-b346)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[Velocity-3.3-346.jar:3.3.0-SNAPSHOT (git-59567512-b346)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]

**Comment by groundbreakingmc** [comment]
![Screenshot_1](https://github.com/james090500/VelocityWhitelist/assets/65243837/63f2d975-20cb-4d4a-af73-62d298f87e42)
I tried to add username to white list and I got error, then i added ip and I got error again... What did I do wrong???
